export {default as Landingpage } from "./Landingpage"
export {default as Homelayout } from "./Homelayout"
export {default as Login } from "./Login"
export {default as Register } from "./Register"
export {default as Error } from "./Error"
export {default as Dashboard } from "./Dashboard"